{{- with .Values }}
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ .tenant.name }}
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  {{- if dig "metrics" "enabled" false .tenant }}
  ## Annotations for MinIO Tenant Pods
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: {{ dig "metrics" "port" 9000 .tenant | quote }}
    prometheus.io/scrape: "true"
    prometheus.io/scheme: {{ dig "metrics" "protocol" "http" .tenant | quote }}
  {{- end }}
{{- if dig "scheduler" "name" "" .tenant }}
scheduler:
  name: {{ dig "scheduler" "name" "" .tenant }}
{{- end }}
spec:
  image: "{{ .image.repository }}:{{ .image.digest | default .image.tag }}"
  imagePullPolicy: {{ dig "image" "pullPolicy" "IfNotPresent" .tenant }}
  {{- if dig "imagePullSecret" "name" "" .tenant }}
  imagePullSecret:
    name: {{ dig "imagePullSecret" "name" "" .tenant }}
  {{- end }}
  ## Secret with default environment variable configurations
  configuration:
    name: {{ .secrets.existingSecret | default .secrets.name }}
  pools:
    {{- range (dig "pools" (list) .tenant) }}
    - servers: {{ dig "servers" 4 . }}
      name: {{ dig "name" "" . }}
      volumesPerServer: {{ dig "volumesPerServer" 4 . }}
      {{- if dig "runtimeClassName" "" . }}
      runtimeClassName: {{ dig "runtimeClassName" "" . }}
      {{- end }}
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: {{ dig "storageClassName" "" . }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ dig "size" "10Gi" . }}
      {{- with (dig "annotations" (dict) .) }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "labels" (dict) .) }}
      labels: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "tolerations" (list) .) }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "nodeSelector" (dict) .) }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "affinity" (dict) .) }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "resources" (dict) .) }}
      resources: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "securityContext" (dict) .) }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "containerSecurityContext" (dict) .) }}
      containerSecurityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "topologySpreadConstraints" (list) .) }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  mountPath: {{ dig "mountPath" "/export" .tenant }}
  subPath: {{ dig "subPath" "/data" .tenant }}
  {{- with (dig "certificate" "externalCaCertSecret" (list) .tenant) }}
  externalCaCertSecret: {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with (dig "certificate" "externalCertSecret" (list) .tenant) }}
  externalCertSecret: {{- toYaml . | nindent 6 }}
  {{- end }}
  requestAutoCert: {{ dig "certificate" "requestAutoCert" false .tenant }}
  {{- if dig "s3" "bucketDNS" false .tenant }}
    {{- fail "Value 'tenant.s3.bucketDNS' is deprecated since Operator v4.3.2, use 'tenant.features.bucketDNS' instead" }}
  {{- end }}
  features:
    bucketDNS: {{ dig "features" "bucketDNS" false .tenant }}
    {{- with (dig "features" "domains" (dict) .tenant) }}
    domains: {{- toYaml . | nindent 6 }}
    {{- end }}
    enableSFTP: {{ dig "features" "enableSFTP" false .tenant }}
  {{- with (dig "buckets" (list) .tenant) }}
  buckets: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "users" (list) .tenant) }}
  users: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "certificate" "certConfig" (dict) .tenant) }}
  certConfig: {{- toYaml . | nindent 4 }}
  {{- end }}
  podManagementPolicy: {{ dig "podManagementPolicy" "Parallel" .tenant }}
  {{- with (dig "readiness" (dict) .tenant) }}
  readiness: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "liveness" (dict) .tenant) }}
  liveness: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "startup" (dict) .tenant) }}
  startup: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "exposeServices" (dict) .tenant) }}
  exposeServices: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if dig "serviceAccountName" "" .tenant }}
  serviceAccountName: {{ dig "serviceAccountName" "" .tenant }}
  {{- end }}
  prometheusOperator: {{ dig "prometheusOperator" "false" .tenant }}
  {{- with (dig "logging" (dict) .tenant) }}
  logging: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "serviceMetadata" (dict) .tenant) }}
  serviceMetadata: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "env" (list) .tenant) }}
  env: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if dig "priorityClassName" "" .tenant }}
  priorityClassName: {{ dig "priorityClassName" "" .tenant }}
  {{- end }}
  {{- if dig "kes" "configuration" false .tenant }}
  kes:
    image: "{{ .kes.image.repository }}:{{ .kes.image.digest | default .kes.image.tag }}"
    {{- with (dig "kes" "env" (list) .tenant) }}
    env: {{- toYaml . | nindent 4 }}
    {{- end }}
    replicas: {{ .tenant.kes.replicas | int }}
    kesSecret:
      name: "kes-configuration"
    imagePullPolicy: {{ .tenant.kes.imagePullPolicy | quote }}
    {{- with (dig "kes" "externalCertSecret" (dict) .tenant) }}
    externalCertSecret: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "kes" "clientCertSecret" (dict) .tenant) }}
    clientCertSecret: {{- toYaml . | nindent 6 }}
    {{- end }}
    ## Key name to be created on the KMS, default is "my-minio-key"
    keyName: {{ .tenant.kes.keyName | quote }}
    {{- with (dig "resources" (dict) .tenant) }}
    resources: {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "nodeSelector" (dict) .tenant) }}
    nodeSelector: {{- toYaml . | nindent 4 }}
    {{- end }}
    affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    tolerations: []
    {{- with (dig "annotations" (dict) .tenant) }}
    annotations: {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "labels" (dict) .tenant) }}
    labels: {{- toYaml . | nindent 4 }}
    {{- end }}
    serviceAccountName: {{ .tenant.kes.serviceAccountName | quote }}
    securityContext:
      runAsUser: {{ .tenant.kes.securityContext.runAsUser | int }}
      runAsGroup: {{ .tenant.kes.securityContext.runAsGroup | int }}
      runAsNonRoot: {{ .tenant.kes.securityContext.runAsNonRoot }}
      fsGroup: {{ .tenant.kes.securityContext.fsGroup | int }}
  {{- end }}
{{- end }}
